### ISSUE TITLE
Problems with psubscribe

### ISSUE THREAD

**Issue by legraina** [acl-dev/acl#51]
Hi,

I'm trying to use the following code and I am not receiving any of the published messages.
What's more the method publish() returns me 1 (as only one connection is listening to the channel).
Do you know why it's not working ? A bug or something wrong on my side ?
Many thanks

```
 // subscribe
    acl::redis_client connection(_redis_addr);
    acl::redis_pubsub sub(&connection);
    const char* pattern = "*";
    int out = sub.psubscribe(pattern, NULL);

    // then listen
    while(!_stop) {
      acl::string channel, message;
      if(sub.get_message(channel, message)) {
          do stuff ...
     }
  }
```

**Comment by zhengshuxin** [comment]
This's a bug in get_message which can't support psubscribe's result. I've just fixed it now.
Thanks.
zsx

**Comment by legraina** [comment]
Thank you, but the bug is not fixed. psubscribe doesn't work now.
Before, in the redis monitor, I was seeing my command line "PSUBSCRIBE" "*".
Now, there is nothing in the monitor, it seems that the client does not send the request anymore on psubscribe.
